return {
	armphasegate = {
		buildangle = 8192,
		buildpic = "ARMTRENCH.DDS",
		buildtime = 1200,
		collisionvolumetype = "Box",
		collisionvolumescales = "60 40 60",
		corpse = "DEAD",
	energycost = 500,
	footprintx = 2,
	footprintz = 2,
	health = 2000,
		maxacc = 0,
		maxdec = 0,
		maxslope = 20,
		maxwaterdepth = 255,
		metalcost = 400,
		objectname = "Units/arm3X3F.s3o",
		seismicsignature = 0,
		sightdistance = 300,
		yardmap = "oooo",
		customparams = {
			phase_togglable = 1,
			model_author = "Doctrine RTS",
			subfolder = "ArmBuildings/Fortification",
			techlevel = 1,
			usebuildinggrounddecal = false,
	},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				damage = 800,
				metal = 150,
				object = "Units/arm3X3F.s3o",
				reclaimable = true,
			},
	},
	},
}
