return {
	armtrench = {
		buildangle = 8192,
		buildpic = "ARMTRENCH.DDS",
		buildtime = 900,
		collisionvolumetype = "Box",
		collisionvolumescales = "90 20 90",
		collisionvolumeoffsets = "0 -25 0",
		corpse = "DEAD",
	energycost = 300,
	footprintx = 3,
	footprintz = 3,
	health = 3000,
		maxacc = 0,
		maxdec = 0,
		maxslope = 20,
		maxwaterdepth = 255,
		metalcost = 250,
			objectname = "Units/arm3X3F.s3o",
		yardmap = "ooooooooo",
		customparams = {
			trench = 1,
			trench_depth = 30,
			model_author = "Doctrine RTS",
			subfolder = "ArmBuildings/Fortification",
			techlevel = 1,
			usebuildinggrounddecal = false,
	},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 600,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 100,
				object = "Units/arm3X3F.s3o",
				reclaimable = true,
			},
	},
	},
}
